version: '3'

services:

 app:
   build: .
   env_file:
     - environment/api.env
   ports:
     - "8000:8000"
   volumes:
     - ./app:/app
   command: >
     sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
   depends_on:
     - db

 db:
   image: postgres:11-alpine
   env_file:
     - ./environment/db.env
   volumes:
     - /dbdata:/var/lib/postgresql/data
