version: '3'

services:

 web:
   build: .
   ports:
     - "8000:8000"
   volumes:
     - .:/app
   command: >
     sh -c "python manage.py wait_for_db &&
            gunicorn core.wsgi:application --bind 0.0.0.0:8000"
   environment:
     - DB_HOST=${DB_HOST}
     - DB_NAME=${DB_NAME}
     - DB_USER=${DB_USER}
     - DB_PASS=${DB_PASS}
     - SECRET_KEY=${SECRET_KEY}
     - OMBDAPI_KEY=${OMBDAPI_KEY}
   depends_on:
     - db

 db:
   image: postgres:11-alpine
   volumes:
     - postgres_data:/var/lib/postgresql/data/
   environment:
     - POSTGRES_DB=${POSTGRES_DB}
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres_data:
