# Generated by Django 3.0.1 on 2020-01-02 09:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200102_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
